### ISSUE TITLE
Order collection table not correct

### ISSUE THREAD

**Issue by krishana** [reydelleon/advanced-magento-tax-report#1]
Please fix it
Remove "mvmt_" from collection table.

 $collection->getSelect()->joinLeft(
            array('order' => 'mvmt_sales_flat_order'),
            'order.entity_id = main_table.parent_id',
            array(
                'status' => 'order.status',
                'created_at' => 'order.created_at',
                'grand_total' => 'SUM(order.grand_total)'))
            ->joinLeft(
                array('order_tax' => 'mvmt_sales_order_tax'),
                'order_tax.order_id = main_table.parent_id',
                array(
                    'county' => 'order_tax.title',
                    'tax_amount' => 'SUM(order_tax.amount)',
                    'tax_rate' => 'order_tax.percent'))
            ->distinct(true);

In your code
 $collection->getSelect()->joinLeft(
            array('order' => 'sales_flat_order'),
            'order.entity_id = main_table.parent_id',
            array(
                'status' => 'order.status',
                'created_at' => 'order.created_at',
                'grand_total' => 'SUM(order.grand_total)'))
            ->joinLeft(
                array('order_tax' => 'sales_order_tax'),
                'order_tax.order_id = main_table.parent_id',
                array(
                    'county' => 'order_tax.title',
                    'tax_amount' => 'SUM(order_tax.amount)',
                    'tax_rate' => 'order_tax.percent'))
            ->distinct(true);

**Comment by reydelleon** [comment]
Following your suggestion, I updated the query in the Grid.php file. Thanks @krishana!
